
# Compiler
CC = gcc

# Libraries
LIBS = -lpthread

# Source file
SRC = exercise1.c

# Output file
OUT = exercise1.exe

all: $(OUT)

$(OUT): $(SRC)
	$(CC) -o $(OUT) $(SRC) $(LIBS)

clean:
	rm -f $(OUT)
