CC = gcc
CFLAGS = -g -Ipthread

all: example1.exe example1_slove.exe

example1.exe: example1.c
	$(CC) $(CFLAGS) -o example1.exe example1.c

example1_slove.exe: example1_slove.c
	$(CC) $(CFLAGS) -o example1_slove.exe example1_slove.c