CC = gcc
CFLAGS = -g -Ipthread

all: exercise1.exe exercise2.exe

exercise1.exe: exercise1.c
	$(CC) $(CFLAGS) -o exercise1.exe exercise1.c

exercise2.exe: exercise2.c
	$(CC) $(CFLAGS) -o exercise2.exe exercise2.c