CC = gcc
CFLAGS = -g -Ipthread

all: example2.exe example2_slove.exe

example2.exe: example2.c
	$(CC) $(CFLAGS) -o example2.exe example2.c

example2_slove.exe: example2_slove.c
	$(CC) $(CFLAGS) -o example2_slove.exe example2_slove.c